# Generated by Django 2.0.3 on 2019-04-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambahcontoh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inserttmbh',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
